@echo off

REM This file was generated by Ember Desktop from the following template:
REM   app/thread/meta-inf/template/em3xx/em3xx-prebuild.bat
REM Please do not edit it directly.

REM Pre Build processing for IAR Workbench.
