// This file is generated by Ember Desktop.  Please do not edit manually.
//
//

bool emberAfOkToSleep(uint32_t durationMs);

void emberAfPluginIdleSleepWakeUp(uint32_t durationMs);

bool emberAfOkToIdle(uint32_t durationMs);

void emberAfPluginIdleSleepActive(uint32_t durationMs);

void emberAfMain(MAIN_FUNCTION_PARAMETERS);

void emberAfInit(void);

void emberAfTick(void);

void emberMarkApplicationBuffers(void);
