// This file is generated by Ember Desktop.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __THREAD_CALLBACKS__
#define __THREAD_CALLBACKS__


#include PLATFORM_HEADER
#include CONFIGURATION_HEADER
#include EMBER_AF_API_EMBER_TYPES
#include EMBER_AF_API_HAL
#include EMBER_AF_API_SIM_EEPROM
#include EMBER_AF_API_STACK
#include EMBER_AF_API_TFTP_BOOTLOADER


/** @brief Main Application Entry Point
 *
 * This is the main application entry point. All applications
 * must implement this function.
 */
int main(MAIN_FUNCTION_PARAMETERS);

/** @brief A callback called in interrupt context whenever a button
 * changes its state.
 *
 * @appusage Must be implemented by the application.  This function should
 * contain the functionality to be executed in response to changes of state
 * in each of the buttons, or callbacks to the appropriate functionality.
 *
 * @param button  The button which has changed state, either BUTTON0 or BUTTON1
 * as defined in the appropriate BOARD_HEADER.
 *
 * @param state   The new state of the button referenced by the button parameter,
 * either ::BUTTON_PRESSED if the button has been pressed or ::BUTTON_RELEASED if
 * the button has been released.
 */
void halButtonIsr(uint8_t button, uint8_t state);

/** @brief Ok To Sleep
 *
 * This function is called by the Idle/Sleep plugin before sleeping.  It is
 * called with interrupts disabled.  The application should return true if the
 * device may sleep or false otherwise.
 *
 * @param durationMs The maximum duration in milliseconds that the device will
 * sleep.
 */
bool emberAfPluginIdleSleepOkToSleepCallback(uint32_t durationMs);

/** @brief Wake Up
 *
 * This function is called by the Idle/Sleep plugin after sleeping.
 *
 * @param durationMs The duration in milliseconds that the device slept.
 */
void emberAfPluginIdleSleepWakeUpCallback(uint32_t durationMs);

/** @brief Ok To Idle
 *
 * This function is called by the Idle/Sleep plugin before idling.  It is called
 * with interrupts disabled.  The application should return true if the device
 * may idle or false otherwise.
 *
 * @param durationMs The maximum duration in milliseconds that the device will
 * idle.
 */
bool emberAfPluginIdleSleepOkToIdleCallback(uint32_t durationMs);

/** @brief Active
 *
 * This function is called by the Idle/Sleep plugin after idling.
 *
 * @param durationMs The duration in milliseconds that the device idled.
 */
void emberAfPluginIdleSleepActiveCallback(uint32_t durationMs);

/** @brief Main
 *
 * This function is called immediately after the application starts executing
 * and can be used to perform initialization that should occur before any other
 * components are initialized.
 */
void emberAfMainCallback(MAIN_FUNCTION_PARAMETERS);

/** @brief Init
 *
 * This function is called after the stack initializes and can be used to
 * perform any additional initialization required at stack startup.  On SoCs,
 * this will generally be called only once: at system startup.  On hosts, this
 * will be called when the NCP initializes, and may be called multiple times
 * during the lifetime of the host application.
 */
void emberAfInitCallback(void);

/** @brief Tick
 *
 * This function is called in each iteration of the main application loop and
 * can be used to perform periodic functions.  The frequency with which this
 * function is called depends on how quickly the main loop runs.  If the
 * application blocks at any time during the main loop, this function will not
 * be called until execution resumes.  On SoC platforms, sleeping and idling
 * will block.  On Unix hosts, process yielding (e.g., via select) will block.
 */
void emberAfTickCallback(void);

/** @brief Mark Application Buffers
 *
 * This function is called when the application must mark its buffers.  Buffers
 * that are not marked will be reclaimed by the stack.
 */
void emberAfMarkApplicationBuffersCallback(void);

/** @brief The Simulated EEPROM callback function, implemented by the
 * application.
 *
 * @param status  An ::EmberStatus error code indicating one of the conditions
 * described below.
 *
 * This callback will report an EmberStatus of
 * ::EMBER_SIM_EEPROM_ERASE_PAGE_GREEN whenever a token is set and a page needs
 * to be erased.  If the main application loop does not periodically
 * call halSimEepromErasePage(), it is best to then erase a page in
 * response to ::EMBER_SIM_EEPROM_ERASE_PAGE_GREEN.
 *
 * This callback will report an EmberStatus of ::EMBER_SIM_EEPROM_ERASE_PAGE_RED
 * when the pages <i>must</i> be erased to prevent data loss.
 * halSimEepromErasePage() needs to be called until it returns 0 to indicate
 * there are no more pages that need to be erased.  Ignoring
 * this indication and not erasing the pages will cause dropping the new data
 * trying to be written.
 *
 * This callback will report an EmberStatus of ::EMBER_SIM_EEPROM_FULL when
 * the new data cannot be written due to unerased pages.  <b>Not erasing
 * pages regularly, not erasing in response to
 * ::EMBER_SIM_EEPROM_ERASE_PAGE_GREEN, or not erasing in response to
 * ::EMBER_SIM_EEPROM_ERASE_PAGE_RED will cause
 * ::EMBER_SIM_EEPROM_FULL and the new data will be lost!.</b>  Any future
 * write attempts will be lost as well.
 *
 * This callback will report an EmberStatus of ::EMBER_SIM_EEPROM_REPAIRING
 * when the Simulated EEPROM needs to repair itself.  While there's nothing
 * for an app to do when the SimEE is going to repair itself (SimEE has to
 * be fully functional for the rest of the system to work), alert the
 * application to the fact that repairing is occuring.  There are debugging
 * scenarios where an app might want to know that repairing is happening;
 * such as monitoring frequency.
 * @note  Common situations will trigger an expected repair, such as using
 *        a new chip or changing token definitions.
 *
 * If the callback ever reports the status ::EMBER_ERR_FLASH_WRITE_INHIBITED or
 * ::EMBER_ERR_FLASH_VERIFY_FAILED, this indicates a catastrophic failure in
 * flash writing, meaning either the address being written is not empty or the
 * write itself has failed.  If ::EMBER_ERR_FLASH_WRITE_INHIBITED is
 * encountered, the function ::halInternalSimEeRepair(false) should be called
 * and the chip should then be reset to allow proper initialization to recover.
 * If ::EMBER_ERR_FLASH_VERIFY_FAILED is encountered the Simulated EEPROM (and
 * tokens) on the specific chip with this error should not be trusted anymore.
 *
 */
void halSimEepromCallback(EmberStatus status);

bool emberVerifyBootloadRequest(const TftpBootloaderBootloadRequest *request);

// Applications that use buffers must mark them by defining this function.
// The stack uses this when reclaiming unused buffers.
void emberMarkApplicationBuffers(void);

/** @brief A callback that allows the application to send a message in
  * response to a poll from a child.
  *
  * This function is called when a child polls,
  * provided that the pending message flag is set for that child
  * (see ::emberSetMessageFlag(). The message should be sent to the child
  * using ::emberSendUnicast() with the ::EMBER_APS_OPTION_POLL_RESPONSE option.
  *
  * If the application includes ::emberPollHanlder(), it must
  * define EMBER_APPLICATION_HAS_POLL_HANDLER in its CONFIGURATION_HEADER.
  *
  * @param childId           The ID of the child that is requesting data.
  *
  * @param transmitExpected  true if the child is expecting an application-
  *     supplied data message.  false otherwise.
  *
  */
void emberPollHandler(EmberNodeId childId, bool transmitExpected);

void emberCoapMessageHandler(const EmberIpv6Address *source,
                             EmberCoapCode code,
                             const uint8_t *token,
                             uint8_t tokenLength,
                             const uint8_t *uriPath,
                             uint16_t uriPathLength,
                             const uint8_t *payload,
                             uint16_t payloadLength);

void emberIpIncomingBeaconHandler(PacketHeader header);

/** @brief  Application callback for an incoming ICMP message.
 *
 * @param ipHeader        Pointer to an IPV6 buffer
 */
void emberIncomingIcmpHandler(Ipv6Header *ipHeader);

/** @brief  Reports an incoming beacon during an active scan. */
void emberActiveScanHandler(const EmberMacBeaconData *beaconData);

/** @brief
 * This is called when a SLAAC or DHCP address has been configured or timed out.
 * A valid lifetime of zero means that the address is no longer available.
 *
 * @param address            the address on the DHCP server (16 bytes)
 * @param validLifetime      the valid lifetime of the address (in seconds)
 * @param preferredLifetime  the preferred lifetime of the address (in seconds)
 * @param addressFlags       address configuration flags (EMBER_GLOBAL_ADDRESS_*)
 */
void emberAddressConfigurationChange(const EmberIpv6Address *address,
                                     uint32_t validLifetime,
                                     uint32_t preferredLifetime,
                                     uint8_t addressFlags);

/** @brief Provides the result of a call to emberAttachToNetwork(). */
void emberAttachToNetworkReturn(EmberStatus status);

/** @brief Return call for emberBecomeCommissioner().  The status is
 * EMBER_SUCCESS if a petition was sent or EMBER_ERR_FATAL if some
 * temporary resource shortage prevented doing so.
 */
void emberBecomeCommissionerReturn(EmberStatus status);

/** @brief Provices the result of a call to emberChangeNodeType():
 * either EMBER_SUCCESS, or EMBER_INVALID_CALL.
 */
void emberChangeNodeTypeReturn(EmberStatus status);

/**
 * @brief Provides the result of a call to emberCommissionNetwork.
 *
 * Returns EMBER_SUCCESS if successful
 *         EMBER_BAD_ARGUMENT if any of the options are wrong
 *         EMBER_INVALID_CALL if the node is already on a network
 *
 * @param status Whether the call to emberCommissionNetwork was successful
 */
void emberCommissionNetworkReturn(EmberStatus status);

/** @brief Reports on the current commissioner state.
 *
 * @param flags    A combination of zero or more of the following:
 * - EMBER_HAVE_COMMISSIONER       a commissioner is active in the network
 * - EMBER_AM_COMMISSIONER         this device is the active commissioner
 * - EMBER_JOINING_ENABLED         joining is enabled
 * - EMBER_JOINING_WITH_STEERING   steering data restricts which devices can join
 *                                 if not set, no restriction, any device can join
 *                                 (significant only when EMBER_JOINING_ENABLED is set)
 *
 * @param commissionerName    The name of the active commissioner, or
 *                            NULL if there is none or the name is not
 *                            known.
 *
 * @param commissionerNameLength    The length of commissonerName.
 */
void emberCommissionerStatusHandler(uint16_t flags,
                                    const uint8_t *commissionerName,
                                    uint8_t commissionerNameLength);

/** @brief Provides the result of a call to ::emberConfigureGateway */
void emberConfigureGatewayReturn(EmberStatus status);

/** @brief A callback invoked to inform the application of the
 * occurrence of an event defined by EmberCounterType, for example,
 * transmissions and receptions at different layers of the stack.
 *
 * The application must define EMBER_APPLICATION_HAS_COUNTER_HANDLER
 * in its CONFIGURATION_HEADER to use this.
 * This function may be called in ISR context, so processing should
 * be kept to a minimum.
 *
 * @param type       The type of the event.
 * @param increment  Specify the increase in the counter's tally.
 *
 */
void emberCounterHandler(EmberCounterType type, uint16_t increment);

/** @brief NCP handler called to process a custom message from the Host.
 *
 * @param message message received
 * @param messageLength length of message
 */
void emberCustomHostToNcpMessageHandler(const uint8_t *message,
                                        uint8_t messageLength);

/** @brief Host handler called to process a custom message from the NCP.
 *
 * @param message message received
 * @param messageLength length of message
 */
void emberCustomNcpToHostMessageHandler(const uint8_t *message,
                                        uint8_t messageLength);

/** @brief For a sleepy end device, report how long the chip went to deep sleep.
 * In a NCP + host setup, the stack reports this to the host app.
 */
void emberDeepSleepCallback(uint16_t sleepDuration);

/** @brief Provides the result of a call to emberDeepSleep(). */
void emberDeepSleepReturn(EmberStatus status);

/** @brief
 * This is called when the stack knows about a new dhcp server or if
 * a dhcp server has become unavailable.
 *
 * "available" means the DHCP server can offer us an address if
 * requested.
 *
 * @param prefix            dhcp server prefix
 * @param prefixLength      length of the prefix
 * @param available         whether this dhcp server is available
 */
void emberDhcpServerChange(const uint8_t *prefix,
                           uint8_t prefixLength,
                           bool available);

/** @brief  Reports the maximum RSSI value measured on the channel.
  *
  * @param channel  The 802.15.4 channel on which the RSSI value was measured.
  *
  * @param maxRssiValue  The maximum RSSI value measured (in units of dBm).
  */
void emberEnergyScanHandler(uint8_t channel, int8_t maxRssiValue);

/** @brief This method is called any time an event is scheduled from within an
 * ISR context. It can be used to determine when to stop a long running sleep
 * to see what application or stack events now need to be processed.
 * @param event The event that was scheduled by the ISR.
 */
void emberEventDelayUpdatedFromIsrHandler(Event *event);

/** @brief
 * This is called when the stack knows about a border router that has
 * an external route to a prefix.
 *
 * @param prefix            external route prefix
 * @param prefixLength      length of the prefix
 * @param available         whether this external route is available.
 */
void emberExternalRouteChange(const uint8_t *prefix,
                              uint8_t prefixLength,
                              bool available);

/** @brief Provides the result of a call to emberFormNetwork(). */
void emberFormNetworkReturn(EmberStatus status);

/** @brief Provides the result of a call to emberGetCcaThreshold(). */
void emberGetCcaThresholdReturn(int8_t threshold);

/** @brief
 * Gets the token information for tokenId = EMBER_CHANNEL_CAL_DATA_TOKEN
 *
 * @param lna          [msb: cal needed? | bit 0-5: lna tune value]
 * @param tempAtLna    [the temp (degC) when the LNA was calibrated]
 * #param modDac       [msb: cal needed? | bit 0-5: modulation DAC tune value]
 * @param tempAtModDac [the temp (degC) when the mod DAC was calibrated]
 */
void emberGetChannelCalDataTokenReturn(uint8_t lna,
                                       int8_t tempAtLna,
                                       uint8_t modDac,
                                       int8_t tempAtModDac);

/** @brief Provides the result of a call to emberGetCounter(). */
void emberGetCounterReturn(EmberCounterType type, uint16_t value);

/** @brief Provides the result of a call to ::emberGetDhcpClients */
void emberGetDhcpClientReturn(const EmberIpv6Address *address);

/** @brief Provides the result of a call to ::emberGetGlobalAddresses
 *
 * @param address             IPv6 global address
 * @param preferredLifetime   Preferred lifetime (in seconds)
 * @param validLifetime       Valid lifetime (in seconds)
 * @param addressFlags        Address configuration flags (EMBER_GLOBAL_ADDRESS_*)
 */
void emberGetGlobalAddressReturn(const EmberIpv6Address *address,
                                 uint32_t preferredLifetime,
                                 uint32_t validLifetime,
                                 uint8_t addressFlags);

/** @brief Provides the result of a call to ::emberGetGlobalPrefix
 *
 * @param borderRouterFlags   Border router flags (EMBER_BORDER_ROUTER_*)
 * @param prefix              Border router prefix
 * @param domainId            Provisioning domain ID
 * @param preferredLifetime   Preferred lifetime (in seconds)
 * @param validLifetime       Valid lifetime (in seconds)
 */
void emberGetGlobalPrefixReturn(uint8_t borderRouterFlags,
                                const uint8_t *prefix,
                                uint8_t domainId,
                                uint32_t preferredLifetime,
                                uint32_t validLifetime);

/** @brief Provides the result of a call to emberGetNetworkDataTlv().
 *
 * @param type the type of TLV returned. This is the same value as
 * the value specified in the emberGetNetworkDataTlv() call.
 * @param index the instance number of the TLV. This is the same value as
 * the value specified in the emberGetNetworkDataTlv() call.
 * @param versionNumber the network data version
 * @param tlv the TLV corresponding to type or NULL.
 * @param tlvLength length of tlv
 */
void emberGetNetworkDataTlvReturn(uint8_t typeByte,
                                  uint8_t index,
                                  uint8_t versionNumber,
                                  const uint8_t *tlv,
                                  uint8_t tlvLength);

/** @brief Provides the result of a call to emberGetRadioPower() on the host. */
void emberGetRadioPowerReturn(int8_t power);

/** @brief Provides the result of a call to emberGetRipEntry(). */
void emberGetRipEntryReturn(uint8_t index, const EmberRipEntry *entry);

/** @brief Provides the result of a call to ::emberGetRoutingLocator
 *
 * @param rloc The Routing Locator as a full IPv6 address.
 */
void emberGetRoutingLocatorReturn(const EmberIpv6Address *rloc);

/** @brief Provides the result of a call to emberGetTxPowerMode() on the host.
 * @return the current tx power mode.
 */
void emberGetTxPowerModeReturn(uint16_t txPowerMode);

/** @brief Provides the result of a call to emberGetVersions(). */
void emberGetVersionsReturn(const uint8_t *versionName,
                            uint16_t managementVersionNumber,
                            uint16_t stackVersionNumber,
                            uint16_t stackBuildNumber,
                            EmberVersionType versionType,
                            const uint8_t *buildTimestamp);

/** @brief  Provides the result of a call to emberInit(). */
void emberInitReturn(EmberStatus status);

/** @brief  Provides the result of a call to emberJoinNetwork(). 
 * 
 * See stack/include/error-def.h for join error codes.
 * 
 * Please note:
 * This function is called as a result of a join as well as after changes to
 * network status that occur naturally during the lifetime of a network.  As a
 * status handler, it is roughly equivalent to emberStackStatusHandler in other
 * stacks.  The application should implement this function and manage those
 * status changes appropriately.
 *
 * If this returns with EMBER_ATTACH_FAILED, it means that the device was able
 * to obtain the commissioning materials from another device (or this material
 * was already pre-commissioned), but for some reason, it failed to complete
 * the attach handshake with a router-eligible device.
 *
 * In this situation, the device will retain its commissioning material, and
 * the application should call ::emberAttachToNetwork() so it can attempt to get
 * on the network.
 *
 * Before making the call to ::emberAttachToNetwork(), please check that the
 * network status is EMBER_JOINED_NETWORK_NO_PARENT.
 */
void emberJoinNetworkReturn(EmberStatus status);

/** @brief Application handler to define "passthrough" packets.
 */
bool emberMacPassthroughFilterHandler(uint8_t *macHeader);

/** @brief Application handler to intercept "passthrough" packets and
 * handle them at the application.
 */
void emberMacPassthroughMessageHandler(PacketHeader header);

/** @brief A callback invoked when the leader data changes.
 *
 * @param leaderData the leader data
 */
void emberLeaderDataHandler(const uint8_t *leaderData);

/** @brief  If implementing event-driven sleep on an NCP host, this method will
 * return the bitmask indicating the stack's current tasks. (see enum above)
 *
 *  The mask ::EMBER_HIGH_PRIORITY_TASKS defines which tasks are high
 *  priority.  Devices should not sleep if any high priority tasks are active.
 *  Active tasks that are not high priority are waiting for
 *  messages to arrive from other devices.  If there are active tasks,
 *  but no high priority ones, the device may sleep but should periodically
 *  wake up and call ::emberPollForData() in order to receive messages.  Parents
 *  will hold messages for ::EMBER_INDIRECT_TRANSMISSION_TIMEOUT milliseconds
 *  before discarding them.
 *
 * @return A bitmask of the stack's active tasks.
 */
void emberOkToNapReturn(uint8_t stateMask);

/** @brief Provides the result of a call to emberPollForData().
 * @param An EmberStatus value:
 * - ::EMBER_SUCCESS      - The poll message has been submitted for transmission
 * - ::EMBER_INVALID_CALL - The node is not a sleepy end device.
 * - ::EMBER_NOT_JOINED   - The node is not part of a network.
 *
 * @param Data pending flag: If true, it means the parent is about to send more
 *                           data, so the application should take note and poll
 *                           more frequently in case of a fragment or indirect
 *                           timeout.
 */
void emberPollForDataReturn(EmberStatus status, bool dataPending);

/** @brief
 * Provides the result of a call to ::emberRequestDhcpAddress
 *
 * This call only indicates the status of the request (EMBER_ERR_FATAL if no
 * DHCP server is found, and EMBER_SUCCESS otherwise).  The assigned IPv6
 * address is returned via ::emberAddressConfigurationChange
 *
 * @param status            Status of DHCP Address Request
 * @param prefix            Prefix requested in ::emberRequestDhcpAddress
 * @param prefixLength      Prefix length requested in ::emberRequestDhcpAddress
 */
void emberRequestDhcpAddressReturn(EmberStatus status,
                                   const uint8_t *prefix,
                                   uint8_t prefixLength);

/** @brief
 * Provides the result of a call to ::emberRequestSlaacAddress
 *
 * This call only indicates the status of the request (EMBER_ERR_FATAL if no
 * SLAAC server is found, and EMBER_SUCCESS otherwise).  The assigned IPv6
 * address is returned via ::emberAddressConfigurationChange
 *
 * @param status            Status of SLAAC Address Request
 * @param prefix            Prefix requested in ::emberRequestSlaacAddress
 * @param prefixLength      Prefix length requested in ::emberRequestSlaacAddress
 */
void emberRequestSlaacAddressReturn(EmberStatus status,
                                    const uint8_t *prefix,
                                    uint8_t prefixLength);

/** @brief  Notifies the application of a reset on the Ember chip
 * due to the indicated cause.
 */
void emberResetMicroHandler(EmberResetCause cause);

/** @brief Provides the result of a call to emberResetNetworkState(). */
void emberResetNetworkStateReturn(EmberStatus status);

/** @brief
 * Provides the result of a call to emberResignGlobalAddress().
 */
void emberResignGlobalAddressReturn(EmberStatus status);

/** @brief Provides the result of a call to emberResumeNetwork(). */
void emberResumeNetworkReturn(EmberStatus status);

/** @brief  Provides the status upon completion of a scan. */
void emberScanReturn(EmberStatus status);

/** @brief Provides the result of a call to emberSendSteeringData(). */
void emberSendSteeringDataReturn(EmberStatus status);

/** @brief Provides the result of a call to emberSetCcaThreshold(). */
void emberSetCcaThresholdReturn(EmberStatus status);

/** @brief Provides the result of a call to emberSetRadioPower() on the host. */
void emberSetRadioPowerReturn(EmberStatus status);

/** @brief Provides the result of a call to emberSetSecurityParameters(). */
void emberSetSecurityParametersReturn(EmberStatus status);

/** @brief Provides the result of a call to emberSetTxPowerMode() on the host. */
void emberSetTxPowerModeReturn(EmberStatus status);

/** @brief
 * This is called when the stack knows about a new SLAAC prefix or if
 * a SLAAC server has become unavailable.
 *
 * "available" means we can configure a SLAAC address.
 *
 * @param prefix            SLAAC prefix
 * @param prefixLength      length of the prefix
 * @param available         whether we can configure an address
 */
void emberSlaacServerChange(const uint8_t *prefix,
                            uint8_t prefixLength,
                            bool available);

/** @brief Provides the result of a call to emberStackPollForData(). */
void emberStackPollForDataReturn(EmberStatus status);

/** @brief Callback to tell the host to start security commissioning
 *
 * @param address parent IP address, 16 bytes
 */
void emberStartHostJoinClientHandler(const uint8_t *parentAddress);

/** @brief
 * This can be stubbed out on the SoC and host app.  It is used by the
 * NCP to update security on the driver when it is instructed to switch
 * the network key by an over the air update.
 *
 */
void emberSwitchToNextNetworkKeyHandler(EmberStatus status);

/** @brief Provides the result of a call to emberSwitchToNextNetworkKey(). */
void emberSwitchToNextNetworkKeyReturn(EmberStatus status);

/**
 * @brief Provides the result of a call to emberState() on the host.
 *
 * @param parameters Current network parameters
 * @param localEui64 The EUI64 of the Ember chip
 * @param networkStatus The current status of the network
 */
void emberStateReturn(const EmberNetworkParameters *parameters,
                      const EmberEui64 *localEui64,
                      EmberNetworkStatus networkStatus);

/** @brief The radio calibration callback function.
 *
 * The Voltage Controlled Oscillator (VCO) can drift with
 * temperature changes.  During every call to ::emberTick(), the stack will
 * check to see if the VCO has drifted.  If the VCO has drifted, the stack
 * will call ::emberRadioNeedsCalibratingHandler() to inform the application
 * that it should perform calibration of the current channel as soon as
 * possible.  Calibration can take up to 150ms.  The default callback function
 * implementation provided here performs calibration immediately.  If the
 * application wishes, it can define its own callback by defining
 * ::EMBER_APPLICATION_HAS_CUSTOM_RADIO_CALIBRATION_CALLBACK in its
 * CONFIGURATION_HEADER.  It can then failsafe any critical processes or
 * peripherals before calling ::emberCalibrateCurrentChannel().  The
 * application must call ::emberCalibrateCurrentChannel() in
 * response to this callback to maintain expected radio performance.
 */
void emberRadioNeedsCalibratingHandler(void);

// Called when a connection is opened to serverPort.
void emberTcpAcceptHandler(uint16_t serverPort, uint8_t fd);

void emberTcpReadHandler(uint8_t fd, uint8_t *buffer, uint16_t count);

void emberTcpStatusHandler(uint8_t fd, uint8_t status);

void emberAddAddressDataReturn(uint16_t shortId);

void emberAssertInfoReturn(const uint8_t *fileName, uint32_t lineNumber);

void emberClearAddressCacheReturn(void);

void emberConfigUartReturn(void);

void emberEchoReturn(const uint8_t *data, uint8_t length);

void emberGetMulticastEntryReturn(uint8_t lastSequence,
                                  uint8_t windowBitmask,
                                  uint8_t dwellQs,
                                  const uint8_t *seed);

void emberGetNetworkKeyInfoReturn(EmberStatus status,
                                  uint32_t sequence,
                                  uint8_t state);

void emberGetNodeStatusReturn(EmberStatus status,
                              uint8_t ripId,
                              EmberNodeId nodeId,
                              uint8_t parentRipId,
                              EmberNodeId parentId,
                              const uint8_t *networkFragmentIdentifier,
                              uint32_t networkFrameCounter);

void emberLookupAddressDataReturn(uint16_t shortId);

void emberNcpUdpStormCompleteHandler(void);

void emberNcpUdpStormReturn(EmberStatus status);

void emberResetNcpAshReturn(void);

void emberSendDoneReturn(void);

void emberSetWakeupSequenceNumberReturn(void);

void emberUartSpeedTestReturn(uint32_t totalBytesSent,
                              uint32_t payloadBytesSent,
                              uint32_t timeout);

/** @brief Receive a multicast */
void emberUdpMulticastHandler(const uint8_t *destinationIpv6Address,
                              const uint8_t *sourceIpv6Address,
                              uint16_t localPort,
                              uint16_t remotePort,
                              uint8_t flags,
                              const uint8_t *packet,
                              uint16_t length);

/** @brief  Application callback for an incoming UDP message.
 *
 * @param destination     IPV6 destination address
 * @param source          IPV6 source address
 * @param localPort       UDP source port
 * @param remotePort      UDP destination port
 * @param payload         UDP transport payload
 * @param payloadLength   payload length
 */
void emberUdpHandler(const uint8_t *destination,
                     const uint8_t *source,
                     uint16_t localPort,
                     uint16_t remotePort,
                     const uint8_t *payload,
                     uint16_t payloadLength);

#endif // __THREAD_CALLBACKS__
