// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED. 
// See the script gen-api-macro-header and read gen-api-macro-header.README.

#if (! defined (RTOS) || ! defined (IP_MODEM_LIBRARY)) // non RTOS targets and RTOS host thread

  #define emApiAbortWakeup emberAbortWakeup
  #define emApiAbortWakeupReturn emberAbortWakeupReturn
  #define emApiActiveScanHandler emberActiveScanHandler
  #define emApiActiveWakeup emberActiveWakeup
  #define emApiActiveWakeupReturn emberActiveWakeupReturn
  #define emApiAddAddressData emberAddAddressData
  #define emApiAddAddressDataReturn emberAddAddressDataReturn
  #define emApiAddressConfigurationChange emberAddressConfigurationChange
  #define emApiAddSteeringEui64 emberAddSteeringEui64
  #define emApiAppEventQueue emberAppEventQueue
  #define emApiAppEvents emberAppEvents
  #define emApiAssertInfoReturn emberAssertInfoReturn
  #define emApiAttachToNetwork emberAttachToNetwork
  #define emApiAttachToNetworkReturn emberAttachToNetworkReturn
  #define emApiBecomeCommissioner emberBecomeCommissioner
  #define emApiBecomeCommissionerReturn emberBecomeCommissionerReturn
  #define emApiChangeNodeType emberChangeNodeType
  #define emApiChangeNodeTypeReturn emberChangeNodeTypeReturn
  #define emApiClearAddressCache emberClearAddressCache
  #define emApiClearAddressCacheReturn emberClearAddressCacheReturn
  #define emApiClearCounters emberClearCounters
  #define emApiCoapMessageHandler emberCoapMessageHandler
  #define emApiCoapIncomingMessageHandler emCoapIncomingMessageHandler
  #define emApiFinishCoapMessage emFinishCoapMessage
  #define emApiRetryCoapMessage emRetryCoapMessage
  #define emApiCommandTable emberCommandTable
  #define emApiCommissionerStatusHandler emberCommissionerStatusHandler
  #define emApiCommissionNetwork emberCommissionNetwork
  #define emApiCommissionNetworkReturn emberCommissionNetworkReturn
  #define emApiConfigUart emberConfigUart
  #define emApiConfigUartReturn emberConfigUartReturn
  #define emApiConfigureGateway emberConfigureGateway
  #define emApiConfigureGatewayReturn emberConfigureGatewayReturn
  #define emApiConfigureNetwork emberConfigureNetwork
  #define emApiConfigureWakeup emberConfigureWakeup
  #define emApiCounterHandler emberCounterHandler
  #define emApiCustomHostToNcpMessage emberCustomHostToNcpMessage
  #define emApiCustomHostToNcpMessageHandler emberCustomHostToNcpMessageHandler
  #define emApiCustomNcpToHostMessage emberCustomNcpToHostMessage
  #define emApiCustomNcpToHostMessageHandler emberCustomNcpToHostMessageHandler
  #define emApiDeepSleep emberDeepSleep
  #define emApiDeepSleepCallback emberDeepSleepCallback
  #define emApiDeepSleepReturn emberDeepSleepReturn
  #define emApiDhcpServerChange emberDhcpServerChange
  #define emApiEcho emberEcho
  #define emApiEchoReturn emberEchoReturn
  #define emApiEnableResetNcpGpio emberEnableResetNcpGpio
  #define emApiEnergyScanHandler emberEnergyScanHandler
  #define emApiEui64 emberEui64
  #define emApiEventDelayUpdatedFromIsrHandler emberEventDelayUpdatedFromIsrHandler
  #define emApiExternalRouteChange emberExternalRouteChange
  #define emApiFfWakeup emberFfWakeup
  #define emApiForceAssert emberForceAssert
  #define emApiFormNetwork emberFormNetwork
  #define emApiFormNetworkReturn emberFormNetworkReturn
  #define emApiGetCcaThreshold emberGetCcaThreshold
  #define emApiGetCcaThresholdReturn emberGetCcaThresholdReturn
  #define emApiGetChannelCalDataTokenReturn emberGetChannelCalDataTokenReturn
  #define emApiGetCommissioner emberGetCommissioner
  #define emApiGetCounter emberGetCounter
  #define emApiGetCounterReturn emberGetCounterReturn
  #define emApiGetDhcpClientReturn emberGetDhcpClientReturn
  #define emApiGetDhcpClients emberGetDhcpClients
  #define emApiGetGlobalAddresses emberGetGlobalAddresses
  #define emApiGetGlobalAddressReturn emberGetGlobalAddressReturn
  #define emApiGetGlobalPrefixes emberGetGlobalPrefixes
  #define emApiGetGlobalPrefixReturn emberGetGlobalPrefixReturn
  #define emApiGetIndexedToken emberGetIndexedToken
  #define emApiGetLocalIpAddress emberGetLocalIpAddress
  #define emApiGetMulticastEntryReturn emberGetMulticastEntryReturn
  #define emApiGetMulticastTable emberGetMulticastTable
  #define emApiGetNetworkDataTlv emberGetNetworkDataTlv
  #define emApiGetNetworkDataTlvReturn emberGetNetworkDataTlvReturn
  #define emApiGetNetworkKeyInfo emberGetNetworkKeyInfo
  #define emApiGetNetworkKeyInfoReturn emberGetNetworkKeyInfoReturn
  #define emApiGetNetworkParameters emberGetNetworkParameters
  #define emApiGetNodeStatus emberGetNodeStatus
  #define emApiGetNodeStatusReturn emberGetNodeStatusReturn
  #define emApiGetPanId emberGetPanId
  #define emApiGetRadioPower emberGetRadioPower
  #define emApiGetRadioPowerReturn emberGetRadioPowerReturn
  #define emApiGetRipEntry emberGetRipEntry
  #define emApiGetRipEntryReturn emberGetRipEntryReturn
  #define emApiGetRoutingLocator emberGetRoutingLocator
  #define emApiGetRoutingLocatorReturn emberGetRoutingLocatorReturn
  #define emApiGetTxPowerMode emberGetTxPowerMode
  #define emApiGetTxPowerModeReturn emberGetTxPowerModeReturn
  #define emApiGetVersions emberGetVersions
  #define emApiGetVersionsReturn emberGetVersionsReturn
  #define emApiGpioCurrentConfig emberGpioCurrentConfig
  #define emApiGpioCurrentConfigReturn emberGpioCurrentConfigReturn
  #define emApiGpioCurrentInput emberGpioCurrentInput
  #define emApiGpioCurrentInputReturn emberGpioCurrentInputReturn
  #define emApiGpioPowerConfig emberGpioPowerConfig
  #define emApiGpioPowerConfigReturn emberGpioPowerConfigReturn
  #define emApiGpioRadioPowerMask emberGpioRadioPowerMask
  #define emApiHostToNcpNoOp emberHostToNcpNoOp
  #define emApiIcmpListen emberIcmpListen
  #define emApiIncomingIcmpHandler emberIncomingIcmpHandler
  #define emApiInit emberInit
  #define emApiInitHost emberInitHost
  #define emApiInitReturn emberInitReturn
  #define emApiIpPing emberIpPing
  #define emApiJoinCommissioned emberJoinCommissioned
  #define emApiJoinNetwork emberJoinNetwork
  #define emApiJoinNetworkReturn emberJoinNetworkReturn
  #define emApiLeaderDataHandler emberLeaderDataHandler
  #define emApiListenForWakeup emberListenForWakeup
  #define emApiListenForWakeupReturn emberListenForWakeupReturn
  #define emApiLookupAddressData emberLookupAddressData
  #define emApiLookupAddressDataReturn emberLookupAddressDataReturn
  #define emApiMacPassthroughFilterHandler emberMacPassthroughFilterHandler
  #define emApiMacPassthroughMessageHandler emberMacPassthroughMessageHandler
  #define emApiMarkApplicationBuffers emberMarkApplicationBuffers
  #define emApiNcpToHostNoOp emberNcpToHostNoOp
  #define emApiNcpUdpStorm emberNcpUdpStorm
  #define emApiNcpUdpStormCompleteHandler emberNcpUdpStormCompleteHandler
  #define emApiNcpUdpStormReturn emberNcpUdpStormReturn
  #define emApiNetworkStatus emberNetworkStatus
  #define emApiOkToNap emberOkToNap
  #define emApiOkToNapReturn emberOkToNapReturn
  #define emApiHostJoinClientComplete emberHostJoinClientComplete
  #define emApiPermitJoining emberPermitJoining
  #define emApiPermitJoiningHandler emberPermitJoiningHandler
  #define emApiPermitJoiningReturn emberPermitJoiningReturn
  #define emApiPing emberPing
  #define emApiPollForData emberPollForData
  #define emApiPollForDataReturn emberPollForDataReturn
  #define emApiRegisterDropIncomingMessageCallback emberRegisterDropIncomingMessageCallback
  #define emApiRegisterSerialTransmitCallback emberRegisterSerialTransmitCallback
  #define emApiRequestDhcpAddress emberRequestDhcpAddress
  #define emApiRequestDhcpAddressReturn emberRequestDhcpAddressReturn
  #define emApiRequestSlaacAddress emberRequestSlaacAddress
  #define emApiRequestSlaacAddressReturn emberRequestSlaacAddressReturn
  #define emApiResetIpDriverAsh emberResetIpDriverAsh
  #define emApiResetMicro emberResetMicro
  #define emApiResetMicroHandler emberResetMicroHandler
  #define emApiResetNcpAsh emberResetNcpAsh
  #define emApiResetNcpAshReturn emberResetNcpAshReturn
  #define emApiResetNcpGpio emberResetNcpGpio
  #define emApiResetNetworkState emberResetNetworkState
  #define emApiResetNetworkStateReturn emberResetNetworkStateReturn
  #define emApiResignGlobalAddress emberResignGlobalAddress
  #define emApiResignGlobalAddressReturn emberResignGlobalAddressReturn
  #define emApiResumeNetwork emberResumeNetwork
  #define emApiResumeNetworkReturn emberResumeNetworkReturn
  #define emApiScanReturn emberScanReturn
  #define emApiSendCommissioningData emberSendCommissioningData
  #define emApiSendDone emberSendDone
  #define emApiSendDoneReturn emberSendDoneReturn
  #define emApiSendSteeringData emberSendSteeringData
  #define emApiSendSteeringDataReturn emberSendSteeringDataReturn
  #define emApiSendUdp emberSendUdp
  #define emApiSetAddressHandler emberSetAddressHandler
  #define emApiSetCcaThreshold emberSetCcaThreshold
  #define emApiSetCcaThresholdReturn emberSetCcaThresholdReturn
  #define emApiSetClockMonitor emberSetClockMonitor
  #define emApiSetCommissioningMacKey emberSetCommissioningMacKey
  #define emApiSetDriverAddressHandler emberSetDriverAddressHandler
  #define emApiSetEui64 emberSetEui64
  #define emApiSetJoiningMode emberSetJoiningMode
  #define emApiSetJoinKey emberSetJoinKey
  #define emApiSetNetworkKeysHandler emberSetNetworkKeysHandler
  #define emApiSetNextNetworkKey emberSetNextNetworkKey
  #define emApiSetNextNetworkKeyReturn emberSetNextNetworkKeyReturn
  #define emApiSetPassthroughPort emberSetPassthroughPort
  #define emApiSetRadioPower emberSetRadioPower
  #define emApiSetRadioPowerReturn emberSetRadioPowerReturn
  #define emApiSetSecurityParameters emberSetSecurityParameters
  #define emApiSetSecurityParametersReturn emberSetSecurityParametersReturn
  #define emApiSetTxPowerMode emberSetTxPowerMode
  #define emApiSetTxPowerModeReturn emberSetTxPowerModeReturn
  #define emApiSetWakeupSequenceNumber emberSetWakeupSequenceNumber
  #define emApiSetWakeupSequenceNumberReturn emberSetWakeupSequenceNumberReturn
  #define emApiSlaacServerChange emberSlaacServerChange
  #define emApiSleepNoTimer emberSleepNoTimer
  #define emApiSleepNoTimerReturn emberSleepNoTimerReturn
  #define emApiStackIdleTimeMs emberStackIdleTimeMs
  #define emApiStackPollForData emberStackPollForData
  #define emApiStackPollForDataReturn emberStackPollForDataReturn
  #define emApiStartHostJoinClientHandler emberStartHostJoinClientHandler
  #define emApiStartScan emberStartScan
  #define emApiStartUartSpeedTest emberStartUartSpeedTest
  #define emApiStartUartStorm emberStartUartStorm
  #define emApiStartUartStormReturn emberStartUartStormReturn
  #define emApiStartWakeup emberStartWakeup
  #define emApiStartWakeupReturn emberStartWakeupReturn
  #define emApiStartXOnXOffTest emberStartXOnXOffTest
  #define emApiState emberState
  #define emApiStateReturn emberStateReturn
  #define emApiStopCommissioning emberStopCommissioning
  #define emApiStopScan emberStopScan
  #define emApiStopUartStorm emberStopUartStorm
  #define emApiStopUartStormReturn emberStopUartStormReturn
  #define emApiSwitchToNextNetworkKey emberSwitchToNextNetworkKey
  #define emApiSwitchToNextNetworkKeyHandler emberSwitchToNextNetworkKeyHandler
  #define emApiSwitchToNextNetworkKeyReturn emberSwitchToNextNetworkKeyReturn
  #define emApiTick emberTick
  #define emApiUartSpeedTestReturn emberUartSpeedTestReturn
  #define emApiUdpHandler emberUdpHandler
  #define emApiUdpListen emberUdpListen
  #define emApiUdpMulticastHandler emberUdpMulticastHandler
  #define emApiWakeupHandler emberWakeupHandler
  #define emApiWakeupState emberWakeupState
  #define emApiWakeupStateReturn emberWakeupStateReturn
  #define mfglibApiEnd mfglibEnd
  #define mfglibApiGetChannel mfglibGetChannel
  #define mfglibApiGetPower mfglibGetPower
  #define mfglibApiGetPowerMode mfglibGetPowerMode
  #define mfglibApiGetSynOffset mfglibGetSynOffset
  #define mfglibApiSendPacket mfglibSendPacket
  #define mfglibApiSetChannel mfglibSetChannel
  #define mfglibApiSetPower mfglibSetPower
  #define mfglibApiSetSynOffset mfglibSetSynOffset
  #define mfglibApiStart mfglibStart
  #define mfglibApiStartStream mfglibStartStream
  #define mfglibApiStartTone mfglibStartTone
  #define mfglibApiStopStream mfglibStopStream
  #define mfglibApiStopTone mfglibStopTone
  #define mfglibApiTestContModCal mfglibTestContModCal

#elif IP_MODEM_LIBRARY // NCP thread in RTOS target

  #define emberAbortWakeup emApiAbortWakeup
  #define emberAbortWakeupReturn emApiAbortWakeupReturn
  #define emberActiveScanHandler emApiActiveScanHandler
  #define emberActiveWakeup emApiActiveWakeup
  #define emberActiveWakeupReturn emApiActiveWakeupReturn
  #define emberAddAddressData emApiAddAddressData
  #define emberAddAddressDataReturn emApiAddAddressDataReturn
  #define emberAddressConfigurationChange emApiAddressConfigurationChange
  #define emberAddSteeringEui64 emApiAddSteeringEui64
  #define emberAppEventQueue emApiAppEventQueue
  #define emberAppEvents emApiAppEvents
  #define emberAssertInfoReturn emApiAssertInfoReturn
  #define emberAttachToNetwork emApiAttachToNetwork
  #define emberAttachToNetworkReturn emApiAttachToNetworkReturn
  #define emberBecomeCommissioner emApiBecomeCommissioner
  #define emberBecomeCommissionerReturn emApiBecomeCommissionerReturn
  #define emberChangeNodeType emApiChangeNodeType
  #define emberChangeNodeTypeReturn emApiChangeNodeTypeReturn
  #define emberClearAddressCache emApiClearAddressCache
  #define emberClearAddressCacheReturn emApiClearAddressCacheReturn
  #define emberClearCounters emApiClearCounters
  #define emberCoapMessageHandler emApiCoapMessageHandler
  #define emCoapIncomingMessageHandler emApiCoapIncomingMessageHandler
  #define emFinishCoapMessage emApiFinishCoapMessage
  #define emRetryCoapMessage emApiRetryCoapMessage
  #define emberCommandTable emApiCommandTable
  #define emberCommissionerStatusHandler emApiCommissionerStatusHandler
  #define emberCommissionNetwork emApiCommissionNetwork
  #define emberCommissionNetworkReturn emApiCommissionNetworkReturn
  #define emberConfigUart emApiConfigUart
  #define emberConfigUartReturn emApiConfigUartReturn
  #define emberConfigureGateway emApiConfigureGateway
  #define emberConfigureGatewayReturn emApiConfigureGatewayReturn
  #define emberConfigureNetwork emApiConfigureNetwork
  #define emberConfigureWakeup emApiConfigureWakeup
  #define emberCounterHandler emApiCounterHandler
  #define emberCustomHostToNcpMessage emApiCustomHostToNcpMessage
  #define emberCustomHostToNcpMessageHandler emApiCustomHostToNcpMessageHandler
  #define emberCustomNcpToHostMessage emApiCustomNcpToHostMessage
  #define emberCustomNcpToHostMessageHandler emApiCustomNcpToHostMessageHandler
  #define emberDeepSleep emApiDeepSleep
  #define emberDeepSleepCallback emApiDeepSleepCallback
  #define emberDeepSleepReturn emApiDeepSleepReturn
  #define emberDhcpServerChange emApiDhcpServerChange
  #define emberEcho emApiEcho
  #define emberEchoReturn emApiEchoReturn
  #define emberEnableResetNcpGpio emApiEnableResetNcpGpio
  #define emberEnergyScanHandler emApiEnergyScanHandler
  #define emberEui64 emApiEui64
  #define emberEventDelayUpdatedFromIsrHandler emApiEventDelayUpdatedFromIsrHandler
  #define emberExternalRouteChange emApiExternalRouteChange
  #define emberFfWakeup emApiFfWakeup
  #define emberForceAssert emApiForceAssert
  #define emberFormNetwork emApiFormNetwork
  #define emberFormNetworkReturn emApiFormNetworkReturn
  #define emberGetCcaThreshold emApiGetCcaThreshold
  #define emberGetCcaThresholdReturn emApiGetCcaThresholdReturn
  #define emberGetChannelCalDataTokenReturn emApiGetChannelCalDataTokenReturn
  #define emberGetCommissioner emApiGetCommissioner
  #define emberGetCounter emApiGetCounter
  #define emberGetCounterReturn emApiGetCounterReturn
  #define emberGetDhcpClientReturn emApiGetDhcpClientReturn
  #define emberGetDhcpClients emApiGetDhcpClients
  #define emberGetGlobalAddresses emApiGetGlobalAddresses
  #define emberGetGlobalAddressReturn emApiGetGlobalAddressReturn
  #define emberGetGlobalPrefixes emApiGetGlobalPrefixes
  #define emberGetGlobalPrefixReturn emApiGetGlobalPrefixReturn
  #define emberGetIndexedToken emApiGetIndexedToken
  #define emberGetLocalIpAddress emApiGetLocalIpAddress
  #define emberGetMulticastEntryReturn emApiGetMulticastEntryReturn
  #define emberGetMulticastTable emApiGetMulticastTable
  #define emberGetNetworkDataTlv emApiGetNetworkDataTlv
  #define emberGetNetworkDataTlvReturn emApiGetNetworkDataTlvReturn
  #define emberGetNetworkKeyInfo emApiGetNetworkKeyInfo
  #define emberGetNetworkKeyInfoReturn emApiGetNetworkKeyInfoReturn
  #define emberGetNetworkParameters emApiGetNetworkParameters
  #define emberGetNodeStatus emApiGetNodeStatus
  #define emberGetNodeStatusReturn emApiGetNodeStatusReturn
  #define emberGetPanId emApiGetPanId
  #define emberGetRadioPower emApiGetRadioPower
  #define emberGetRadioPowerReturn emApiGetRadioPowerReturn
  #define emberGetRipEntry emApiGetRipEntry
  #define emberGetRipEntryReturn emApiGetRipEntryReturn
  #define emberGetRoutingLocator emApiGetRoutingLocator
  #define emberGetRoutingLocatorReturn emApiGetRoutingLocatorReturn
  #define emberGetTxPowerMode emApiGetTxPowerMode
  #define emberGetTxPowerModeReturn emApiGetTxPowerModeReturn
  #define emberGetVersions emApiGetVersions
  #define emberGetVersionsReturn emApiGetVersionsReturn
  #define emberGpioCurrentConfig emApiGpioCurrentConfig
  #define emberGpioCurrentConfigReturn emApiGpioCurrentConfigReturn
  #define emberGpioCurrentInput emApiGpioCurrentInput
  #define emberGpioCurrentInputReturn emApiGpioCurrentInputReturn
  #define emberGpioPowerConfig emApiGpioPowerConfig
  #define emberGpioPowerConfigReturn emApiGpioPowerConfigReturn
  #define emberGpioRadioPowerMask emApiGpioRadioPowerMask
  #define emberHostToNcpNoOp emApiHostToNcpNoOp
  #define emberIcmpListen emApiIcmpListen
  #define emberIncomingIcmpHandler emApiIncomingIcmpHandler
  #define emberInit emApiInit
  #define emberInitHost emApiInitHost
  #define emberInitReturn emApiInitReturn
  #define emberIpPing emApiIpPing
  #define emberJoinCommissioned emApiJoinCommissioned
  #define emberJoinNetwork emApiJoinNetwork
  #define emberJoinNetworkReturn emApiJoinNetworkReturn
  #define emberLeaderDataHandler emApiLeaderDataHandler
  #define emberListenForWakeup emApiListenForWakeup
  #define emberListenForWakeupReturn emApiListenForWakeupReturn
  #define emberLookupAddressData emApiLookupAddressData
  #define emberLookupAddressDataReturn emApiLookupAddressDataReturn
  #define emberMacPassthroughFilterHandler emApiMacPassthroughFilterHandler
  #define emberMacPassthroughMessageHandler emApiMacPassthroughMessageHandler
  #define emberMarkApplicationBuffers emApiMarkApplicationBuffers
  #define emberNcpToHostNoOp emApiNcpToHostNoOp
  #define emberNcpUdpStorm emApiNcpUdpStorm
  #define emberNcpUdpStormCompleteHandler emApiNcpUdpStormCompleteHandler
  #define emberNcpUdpStormReturn emApiNcpUdpStormReturn
  #define emberNetworkStatus emApiNetworkStatus
  #define emberOkToNap emApiOkToNap
  #define emberOkToNapReturn emApiOkToNapReturn
  #define emberHostJoinClientComplete emApiHostJoinClientComplete
  #define emberPermitJoining emApiPermitJoining
  #define emberPermitJoiningHandler emApiPermitJoiningHandler
  #define emberPermitJoiningReturn emApiPermitJoiningReturn
  #define emberPing emApiPing
  #define emberPollForData emApiPollForData
  #define emberPollForDataReturn emApiPollForDataReturn
  #define emberRegisterDropIncomingMessageCallback emApiRegisterDropIncomingMessageCallback
  #define emberRegisterSerialTransmitCallback emApiRegisterSerialTransmitCallback
  #define emberRequestDhcpAddress emApiRequestDhcpAddress
  #define emberRequestDhcpAddressReturn emApiRequestDhcpAddressReturn
  #define emberRequestSlaacAddress emApiRequestSlaacAddress
  #define emberRequestSlaacAddressReturn emApiRequestSlaacAddressReturn
  #define emberResetIpDriverAsh emApiResetIpDriverAsh
  #define emberResetMicro emApiResetMicro
  #define emberResetMicroHandler emApiResetMicroHandler
  #define emberResetNcpAsh emApiResetNcpAsh
  #define emberResetNcpAshReturn emApiResetNcpAshReturn
  #define emberResetNcpGpio emApiResetNcpGpio
  #define emberResetNetworkState emApiResetNetworkState
  #define emberResetNetworkStateReturn emApiResetNetworkStateReturn
  #define emberResignGlobalAddress emApiResignGlobalAddress
  #define emberResignGlobalAddressReturn emApiResignGlobalAddressReturn
  #define emberResumeNetwork emApiResumeNetwork
  #define emberResumeNetworkReturn emApiResumeNetworkReturn
  #define emberScanReturn emApiScanReturn
  #define emberSendCommissioningData emApiSendCommissioningData
  #define emberSendDone emApiSendDone
  #define emberSendDoneReturn emApiSendDoneReturn
  #define emberSendSteeringData emApiSendSteeringData
  #define emberSendSteeringDataReturn emApiSendSteeringDataReturn
  #define emberSendUdp emApiSendUdp
  #define emberSetAddressHandler emApiSetAddressHandler
  #define emberSetCcaThreshold emApiSetCcaThreshold
  #define emberSetCcaThresholdReturn emApiSetCcaThresholdReturn
  #define emberSetClockMonitor emApiSetClockMonitor
  #define emberSetCommissioningMacKey emApiSetCommissioningMacKey
  #define emberSetDriverAddressHandler emApiSetDriverAddressHandler
  #define emberSetEui64 emApiSetEui64
  #define emberSetJoiningMode emApiSetJoiningMode
  #define emberSetJoinKey emApiSetJoinKey
  #define emberSetNetworkKeysHandler emApiSetNetworkKeysHandler
  #define emberSetNextNetworkKey emApiSetNextNetworkKey
  #define emberSetNextNetworkKeyReturn emApiSetNextNetworkKeyReturn
  #define emberSetPassthroughPort emApiSetPassthroughPort
  #define emberSetRadioPower emApiSetRadioPower
  #define emberSetRadioPowerReturn emApiSetRadioPowerReturn
  #define emberSetSecurityParameters emApiSetSecurityParameters
  #define emberSetSecurityParametersReturn emApiSetSecurityParametersReturn
  #define emberSetTxPowerMode emApiSetTxPowerMode
  #define emberSetTxPowerModeReturn emApiSetTxPowerModeReturn
  #define emberSetWakeupSequenceNumber emApiSetWakeupSequenceNumber
  #define emberSetWakeupSequenceNumberReturn emApiSetWakeupSequenceNumberReturn
  #define emberSlaacServerChange emApiSlaacServerChange
  #define emberSleepNoTimer emApiSleepNoTimer
  #define emberSleepNoTimerReturn emApiSleepNoTimerReturn
  #define emberStackIdleTimeMs emApiStackIdleTimeMs
  #define emberStackPollForData emApiStackPollForData
  #define emberStackPollForDataReturn emApiStackPollForDataReturn
  #define emberStartHostJoinClientHandler emApiStartHostJoinClientHandler
  #define emberStartScan emApiStartScan
  #define emberStartUartSpeedTest emApiStartUartSpeedTest
  #define emberStartUartStorm emApiStartUartStorm
  #define emberStartUartStormReturn emApiStartUartStormReturn
  #define emberStartWakeup emApiStartWakeup
  #define emberStartWakeupReturn emApiStartWakeupReturn
  #define emberStartXOnXOffTest emApiStartXOnXOffTest
  #define emberState emApiState
  #define emberStateReturn emApiStateReturn
  #define emberStopCommissioning emApiStopCommissioning
  #define emberStopScan emApiStopScan
  #define emberStopUartStorm emApiStopUartStorm
  #define emberStopUartStormReturn emApiStopUartStormReturn
  #define emberSwitchToNextNetworkKey emApiSwitchToNextNetworkKey
  #define emberSwitchToNextNetworkKeyHandler emApiSwitchToNextNetworkKeyHandler
  #define emberSwitchToNextNetworkKeyReturn emApiSwitchToNextNetworkKeyReturn
  #define emberTick emApiTick
  #define emberUartSpeedTestReturn emApiUartSpeedTestReturn
  #define emberUdpHandler emApiUdpHandler
  #define emberUdpListen emApiUdpListen
  #define emberUdpMulticastHandler emApiUdpMulticastHandler
  #define emberWakeupHandler emApiWakeupHandler
  #define emberWakeupState emApiWakeupState
  #define emberWakeupStateReturn emApiWakeupStateReturn
  #define mfglibEnd mfglibApiEnd
  #define mfglibGetChannel mfglibApiGetChannel
  #define mfglibGetPower mfglibApiGetPower
  #define mfglibGetPowerMode mfglibApiGetPowerMode
  #define mfglibGetSynOffset mfglibApiGetSynOffset
  #define mfglibSendPacket mfglibApiSendPacket
  #define mfglibSetChannel mfglibApiSetChannel
  #define mfglibSetPower mfglibApiSetPower
  #define mfglibSetSynOffset mfglibApiSetSynOffset
  #define mfglibStart mfglibApiStart
  #define mfglibStartStream mfglibApiStartStream
  #define mfglibStartTone mfglibApiStartTone
  #define mfglibStopStream mfglibApiStopStream
  #define mfglibStopTone mfglibApiStopTone
  #define mfglibTestContModCal mfglibApiTestContModCal

#endif

