// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED. 
// See the script gen-api-macro-header and read gen-api-macro-header.README.

#if defined(RTOS) && defined(IP_MODEM_LIBRARY) // NCP thread in RTOS target

  #undef emberAbortWakeup
  #undef emberAbortWakeupReturn
  #undef emberActiveScanHandler
  #undef emberActiveWakeup
  #undef emberActiveWakeupReturn
  #undef emberAddAddressData
  #undef emberAddAddressDataReturn
  #undef emberAddressConfigurationChange
  #undef emberAddSteeringEui64
  #undef emberAppEventQueue
  #undef emberAppEvents
  #undef emberAssertInfoReturn
  #undef emberAttachToNetwork
  #undef emberAttachToNetworkReturn
  #undef emberBecomeCommissioner
  #undef emberBecomeCommissionerReturn
  #undef emberChangeNodeType
  #undef emberChangeNodeTypeReturn
  #undef emberClearAddressCache
  #undef emberClearAddressCacheReturn
  #undef emberClearCounters
  #undef emberCoapMessageHandler
  #undef emCoapIncomingMessageHandler
  #undef emFinishCoapMessage
  #undef emRetryCoapMessage
  #undef emberCommandTable
  #undef emberCommissionerStatusHandler
  #undef emberCommissionNetwork
  #undef emberCommissionNetworkReturn
  #undef emberConfigUart
  #undef emberConfigUartReturn
  #undef emberConfigureGateway
  #undef emberConfigureGatewayReturn
  #undef emberConfigureNetwork
  #undef emberConfigureWakeup
  #undef emberCounterHandler
  #undef emberCustomHostToNcpMessage
  #undef emberCustomHostToNcpMessageHandler
  #undef emberCustomNcpToHostMessage
  #undef emberCustomNcpToHostMessageHandler
  #undef emberDeepSleep
  #undef emberDeepSleepCallback
  #undef emberDeepSleepReturn
  #undef emberDhcpServerChange
  #undef emberEcho
  #undef emberEchoReturn
  #undef emberEnableResetNcpGpio
  #undef emberEnergyScanHandler
  #undef emberEui64
  #undef emberEventDelayUpdatedFromIsrHandler
  #undef emberExternalRouteChange
  #undef emberFfWakeup
  #undef emberForceAssert
  #undef emberFormNetwork
  #undef emberFormNetworkReturn
  #undef emberGetCcaThreshold
  #undef emberGetCcaThresholdReturn
  #undef emberGetChannelCalDataTokenReturn
  #undef emberGetCommissioner
  #undef emberGetCounter
  #undef emberGetCounterReturn
  #undef emberGetDhcpClientReturn
  #undef emberGetDhcpClients
  #undef emberGetGlobalAddresses
  #undef emberGetGlobalAddressReturn
  #undef emberGetGlobalPrefixes
  #undef emberGetGlobalPrefixReturn
  #undef emberGetIndexedToken
  #undef emberGetLocalIpAddress
  #undef emberGetMulticastEntryReturn
  #undef emberGetMulticastTable
  #undef emberGetNetworkDataTlv
  #undef emberGetNetworkDataTlvReturn
  #undef emberGetNetworkKeyInfo
  #undef emberGetNetworkKeyInfoReturn
  #undef emberGetNetworkParameters
  #undef emberGetNodeStatus
  #undef emberGetNodeStatusReturn
  #undef emberGetPanId
  #undef emberGetRadioPower
  #undef emberGetRadioPowerReturn
  #undef emberGetRipEntry
  #undef emberGetRipEntryReturn
  #undef emberGetRoutingLocator
  #undef emberGetRoutingLocatorReturn
  #undef emberGetTxPowerMode
  #undef emberGetTxPowerModeReturn
  #undef emberGetVersions
  #undef emberGetVersionsReturn
  #undef emberGpioCurrentConfig
  #undef emberGpioCurrentConfigReturn
  #undef emberGpioCurrentInput
  #undef emberGpioCurrentInputReturn
  #undef emberGpioPowerConfig
  #undef emberGpioPowerConfigReturn
  #undef emberGpioRadioPowerMask
  #undef emberHostToNcpNoOp
  #undef emberIcmpListen
  #undef emberIncomingIcmpHandler
  #undef emberInit
  #undef emberInitHost
  #undef emberInitReturn
  #undef emberIpPing
  #undef emberJoinCommissioned
  #undef emberJoinNetwork
  #undef emberJoinNetworkReturn
  #undef emberLeaderDataHandler
  #undef emberListenForWakeup
  #undef emberListenForWakeupReturn
  #undef emberLookupAddressData
  #undef emberLookupAddressDataReturn
  #undef emberMacPassthroughFilterHandler
  #undef emberMacPassthroughMessageHandler
  #undef emberMarkApplicationBuffers
  #undef emberNcpToHostNoOp
  #undef emberNcpUdpStorm
  #undef emberNcpUdpStormCompleteHandler
  #undef emberNcpUdpStormReturn
  #undef emberNetworkStatus
  #undef emberOkToNap
  #undef emberOkToNapReturn
  #undef emberHostJoinClientComplete
  #undef emberPermitJoining
  #undef emberPermitJoiningHandler
  #undef emberPermitJoiningReturn
  #undef emberPing
  #undef emberPollForData
  #undef emberPollForDataReturn
  #undef emberRegisterDropIncomingMessageCallback
  #undef emberRegisterSerialTransmitCallback
  #undef emberRequestDhcpAddress
  #undef emberRequestDhcpAddressReturn
  #undef emberRequestSlaacAddress
  #undef emberRequestSlaacAddressReturn
  #undef emberResetIpDriverAsh
  #undef emberResetMicro
  #undef emberResetMicroHandler
  #undef emberResetNcpAsh
  #undef emberResetNcpAshReturn
  #undef emberResetNcpGpio
  #undef emberResetNetworkState
  #undef emberResetNetworkStateReturn
  #undef emberResignGlobalAddress
  #undef emberResignGlobalAddressReturn
  #undef emberResumeNetwork
  #undef emberResumeNetworkReturn
  #undef emberScanReturn
  #undef emberSendCommissioningData
  #undef emberSendDone
  #undef emberSendDoneReturn
  #undef emberSendSteeringData
  #undef emberSendSteeringDataReturn
  #undef emberSendUdp
  #undef emberSetAddressHandler
  #undef emberSetCcaThreshold
  #undef emberSetCcaThresholdReturn
  #undef emberSetClockMonitor
  #undef emberSetCommissioningMacKey
  #undef emberSetDriverAddressHandler
  #undef emberSetEui64
  #undef emberSetJoiningMode
  #undef emberSetJoinKey
  #undef emberSetNetworkKeysHandler
  #undef emberSetNextNetworkKey
  #undef emberSetNextNetworkKeyReturn
  #undef emberSetPassthroughPort
  #undef emberSetRadioPower
  #undef emberSetRadioPowerReturn
  #undef emberSetSecurityParameters
  #undef emberSetSecurityParametersReturn
  #undef emberSetTxPowerMode
  #undef emberSetTxPowerModeReturn
  #undef emberSetWakeupSequenceNumber
  #undef emberSetWakeupSequenceNumberReturn
  #undef emberSlaacServerChange
  #undef emberSleepNoTimer
  #undef emberSleepNoTimerReturn
  #undef emberStackIdleTimeMs
  #undef emberStackPollForData
  #undef emberStackPollForDataReturn
  #undef emberStartHostJoinClientHandler
  #undef emberStartScan
  #undef emberStartUartSpeedTest
  #undef emberStartUartStorm
  #undef emberStartUartStormReturn
  #undef emberStartWakeup
  #undef emberStartWakeupReturn
  #undef emberStartXOnXOffTest
  #undef emberState
  #undef emberStateReturn
  #undef emberStopCommissioning
  #undef emberStopScan
  #undef emberStopUartStorm
  #undef emberStopUartStormReturn
  #undef emberSwitchToNextNetworkKey
  #undef emberSwitchToNextNetworkKeyHandler
  #undef emberSwitchToNextNetworkKeyReturn
  #undef emberTick
  #undef emberUartSpeedTestReturn
  #undef emberUdpHandler
  #undef emberUdpListen
  #undef emberUdpMulticastHandler
  #undef emberWakeupHandler
  #undef emberWakeupState
  #undef emberWakeupStateReturn
  #undef mfglibEnd
  #undef mfglibGetChannel
  #undef mfglibGetPower
  #undef mfglibGetPowerMode
  #undef mfglibGetSynOffset
  #undef mfglibSendPacket
  #undef mfglibSetChannel
  #undef mfglibSetPower
  #undef mfglibSetSynOffset
  #undef mfglibStart
  #undef mfglibStartStream
  #undef mfglibStartTone
  #undef mfglibStopStream
  #undef mfglibStopTone
  #undef mfglibTestContModCal

#endif

